### ISSUE TITLE
Cannot run demo for AMM

### ISSUE THREAD

**Issue by Nashtare** [starkware-libs/cairo-lang#11]
I wanted to compile and run the demo for automated market maker in `cairo-lang/src/demo/amm_demo/amm.cairo` but I could not run the compiled program. When calling `cairo-run --program=test_compiled.json --print_output` I get this error:

`Error: Builtins {'output', 'pedersen', 'range_check'} are not present in layout "plain"`

I am running inside the python virtual environment. Is there something I am missing here?

**Comment by mfaulk** [comment]
The "plain" layout does not contain any builtins. You can specify a different layout for cairo-run, like `--layout=small`

For more, see https://www.cairo-lang.org/docs/how_cairo_works/builtins.html#layouts

**Comment by Nashtare** [comment]
Hmmm... calling `cairo-run --program=test_compiled.json --print_output `--layout=small` gives me[

`amm.cairo:284:5: Error at pc=0:544:
Got an exception while executing a hint.
    %{
    ^^
Traceback (most recent call last):
  File "amm.cairo", line 290, in <module>
    program_input['token_a_balance']
KeyError: 'token_a_balance'`

**Comment by perama-v** [comment]
Hey @Nashtare, when calling `cairo-run` on a compiled program that has a `program_input`, these come from an external file. The path of the file (E.g., `amm_input.json` in the same directory as the compiled program) must be specified, which is achieved with the `--program-input=amm_input.json` flag.

The key is from a key-value pair in that `.json` file. If you create the file and populate with the values found [in the docs](https://www.cairo-lang.org/docs/hello_cairo/amm.html), (search for `amm_input.json`).

```
cairo-compile amm.cairo --output amm_compiled.json

cairo-run --program=amm_compiled.json \
    --print_output --layout=small \
    --program_input=amm_input.json
```

If you want a second source, I did an alternative walkthough of the demo [here](https://perama-v.github.io/cairo/amm-demo/) which also covers this (search `--program-input`).

**Comment by Nashtare** [comment]
Ah right I was missing the input file. Working like a charm now, thank you! Guess this can be closed now
