### ISSUE TITLE
Support ARM64 architecture by upgrading to python@3.9

### ISSUE THREAD

**Issue by Michael-A-Heuer** [starkware-libs/cairo-lang#14]
Python 3.7 does not support ARM64 architecture (e.g. Apple Silicon M1 chips), but 3.9 does (https://docs.python.org/3/whatsnew/3.9.html).
Please consider supporting ARM64 for cairo-lang because a significant fraction of the smart contract devs use MacBooks with an Apple M1 chip.

**Comment by miz2miz** [comment]
i can use python@3.7 on m1_mac_rosseta 
and install cairo smoothly.

**Comment by milancermak** [comment]
I just installed v0.4.1 in a 3.9.6 virtualenv without a problem; macOS 11.6, M1 Macbook.
