### ISSUE TITLE
request: support eth-hash >= 0.3.2

### ISSUE THREAD

**Issue by unparalleled-js** [starkware-libs/cairo-lang#30]
# Feature Request

## Issue

Right now, `eth-hash` is pinned to 0.2.0. Other dependencies in my project require `eth-hash` >= `0.3.2`. I am wondering if there is anything we can do?

## Possible Solution

Either upgrading `eth-hash` to `>= 0.3.2` or relaxing the pin constraints

**Comment by trevis-dev** [comment]
This also comes up in a fresh install of cairo-lang for another of its dependencies. Was it `eth-utils` ?

**Comment by unparalleled-js** [comment]
It seems like this issue has been resolved! I think we can close :) Thank you
