### ISSUE TITLE
Python doesn't properly handle large negative numbers

### ISSUE THREAD

**Issue by timlucmiptev** [starkware-libs/cairo-lang#32]
I have the number `-1024168008553002790667416331076178940052697074220694435907157227142754829457`, the result of a Pedersen hashing. When I try to access it using Python (i.e. as a hint), I get `2594334780113128423029906452018891165570410141110902264065934828993117191024`, although running `serialize_word` on the value confirms that it's the `-1024...` one.

I assume this is either some kind of overflow in Python, or an issue with negative numbers? I need to access the hash value inside a hint , so this is tricky behavior to work with.

**Comment by unparalleled-js** [comment]
As far as I know, there is no overflow with python `long`.

And when I do:

```python
>>> x = -1024168008553002790667416331076178940052697074220694435907157227142754829457
>>> x
-1024168008553002790667416331076178940052697074220694435907157227142754829457
>>> x += 1
>>> x
-1024168008553002790667416331076178940052697074220694435907157227142754829456
```

^ it seems to be fine.

>  When I try to access it using Python (i.e. as a hint)

What does this entail?

**Comment by timlucmiptev** [comment]
Sure, let me give a clear example. Assume the below is in `main`:

```
  local x = -1024168008553002790667416331076178940052697074220694435907157227142754829457
  local y = 1024168008553002790667416331076178940052697074220694435907157227142754829457
  %{ print(ids.x) %}
  %{ print(ids.y) %}
  serialize_word(x)
  serialize_word(y)
  ```

Running this gives output:
```
2594334780113128423029906452018891165570410141110902264065934828993117191024
1024168008553002790667416331076178940052697074220694435907157227142754829457
Program output:
  -1024168008553002790667416331076178940052697074220694435907157227142754829457
  1024168008553002790667416331076178940052697074220694435907157227142754829457
```

**Comment by timlucmiptev** [comment]
Looks like this is due to "negative" numbers just being positive numbers in the upper part of the felt range, so I'll close this and maybe PR to docs.
