### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Mapping' in Python 3.10

### ISSUE THREAD

**Issue by lambda-0x** [starkware-libs/cairo-lang#38]
`frozendict=1.2` uses deprecated (in python3.10) way to import `Mapping`. https://bugs.python.org/issue46354

Upgrade to new version of `frozendict` to add support for python 3.10

**Comment by mjolk** [comment]
I'm astonished, is arch the only distro with up to date python?

**Comment by drgorillamd** [comment]
> I'm astonished, is arch the only distro with up to date python?
> 
> edit: nvm installed 3.7.12 w pyenv

Quick tip for Ubuntu 22.04 users bumping into the same issue (Python3.10 being standard): use brew to install pyenv and see https://github.com/pyenv/pyenv/issues/2293#issuecomment-1123801331

**Comment by unparalleled-js** [comment]
Bump on this, the warnings even when not using Python 3.10 is distracting in testing environments.

**Comment by milancermak** [comment]
@unparalleled-js Try running your tests with `--disable-warnings`. You can put that in `pytest.ini` so you don't have to repeat the arg on the command line all the time:

```
[pytest]
addopts = --disable-warnings
```

**Comment by jney** [comment]
same issue on osx

**Comment by unparalleled-js** [comment]
> @unparalleled-js Try running your tests with `--disable-warnings`.

Thank you! There are some warnings I would like to see. Plus, I work on a testing framework so our users would also have to do this and may not wish to. I am pushing for a zero-warning in the framework goal, so all warnings are valid user warnings that they should see.

**Comment by alofeoluwafemi** [comment]
I resolved this issue by upgrading the package `fronzendict`. `pip3 install frozendict -U`

**Comment by lambda-0x** [comment]
Looks like wouldn't need to worry about this now. Checkout https://github.com/starkware-libs/cairo
