### ISSUE TITLE
Encountered error while trying to install package.

### ISSUE THREAD

**Issue by adust09** [starkware-libs/cairo-lang#40]
I run 'pip3 install cairo-lang', show error below.
```
 In file included from src/curveMath.c:1:
      src/curveMath.h:6:10: fatal error: 'gmp.h' file not found
      #include <gmp.h>
               ^~~~~~~
      1 error generated.
      error: command 'clang' failed with exit status 1
      [end of output]
```

I acctualy did 'brew install gmp', but show this message.
does anyone know about solution?

- Mac OS Montery(v12.2.1)
- Applle Silicon

**Comment by namrapatel** [comment]
@adust09 See this link for potential solutions, (2) worked for me: https://github.com/OpenZeppelin/nile/issues/22

**Comment by adust09** [comment]
thanks bro, It work well!
