### ISSUE TITLE
Error when trying to use verify_eth_signature

### ISSUE THREAD

**Issue by JulissaDantes** [starkware-libs/cairo-lang#64]
Using the 0.8.2.1 version of Cairo-lang I attempt to use the `verify_eth_signature` located inside `starkware.cairo.common.cairo_secp.signature` I get the following error:
```
 /com.docker.devenvironments.code/.tox/default/lib/python3.7/site-packages/starkware/cairo/common/cairo_secp/signature.cairo:209:44: Unknown identifier 'bitwise_ptr'.
E           func verify_eth_signature{range_check_ptr, bitwise_ptr : BitwiseBuiltin*, keccak_ptr : felt*}(
E                                                      ^***************************^
```
![Screen Shot 2022-05-18 at 4 06 09 PM](https://user-images.githubusercontent.com/8561085/169146549-fb9f394c-f5c4-49ea-acb0-5a76ed242679.png)

**Comment by pscott** [comment]
I think the function calling `verify_eth_signature` needs to have the `bitwise_ptr: BitwiseBuiltin*` hint too in order to "give" it to `verify_eth_signature`. Can you share the code somehwer maybe? :D

**Comment by JulissaDantes** [comment]
Thank you, you were absolutely right. But now Im having trouble with another implicit argument, this is how Im calling it:
```
func is_valid_eth_signature{
            syscall_ptr : felt*,
            pedersen_ptr : HashBuiltin*,
            range_check_ptr,
            bitwise_ptr: BitwiseBuiltin*,
            keccak_ptr : felt*
        }(
            hash: BigInt3,
            signature_len: felt,
            signature: BigInt3*,
            nonce: felt
        ) -> ():
        let (_public_key) = get_public_key()
        let (_current_nonce) = get_nonce()

        # validate nonce
        assert _current_nonce = nonce


        # This interface expects a signature pointer and length to make
        # no assumption about signature validation schemes.
        # But this implementation does, and it expects a (sig_r, sig_s) pair.
        let sig_r = signature[0]
        let sig_s = signature[1]

        verify_eth_signature(
            msg_hash=hash,
            r=sig_r,
            s=sig_s,
            v=0,
            eth_address=_public_key)

        return ()
end
```
But that returns:
```
starkware.cairo.lang.compiler.preprocessor.preprocessor_error.PreprocessorError: /com.docker.devenvironments.code/src/contracts/EthAccount.cairo:93:13: Unexpected implicit argument 'keccak_ptr' in an external function.
E                           keccak_ptr : felt*
E                           ^********^
```
And if I don't include keccak_ptr it throws:
```
E           starkware.cairo.lang.compiler.preprocessor.preprocessor_error.PreprocessorError: /com.docker.devenvironments.code/src/contracts/EthAccount.cairo:112:9: While trying to retrieve the implicit argument 'keccak_ptr' in:
E                   verify_eth_signature(
E                   ^*******************^
E           /com.docker.devenvironments.code/.tox/default/lib/python3.7/site-packages/starkware/cairo/common/cairo_secp/signature.cairo:209:75: Unknown identifier 'keccak_ptr'.
E           func verify_eth_signature{range_check_ptr, bitwise_ptr : BitwiseBuiltin*, keccak_ptr : felt*}(
E         
                                                                        ^****************^
```    
Do you know how can I solve this?

**Comment by pscott** [comment]
> Thank you, you were absolutely right. But now Im having trouble with another implicit argument, this is how Im calling it:
> 
> ```
> func is_valid_eth_signature{
>             syscall_ptr : felt*,
>             pedersen_ptr : HashBuiltin*,
>             range_check_ptr,
>             bitwise_ptr: BitwiseBuiltin*,
>             keccak_ptr : felt*
>         }(
>             hash: BigInt3,
>             signature_len: felt,
>             signature: BigInt3*,
>             nonce: felt
>         ) -> ():
>         let (_public_key) = get_public_key()
>         let (_current_nonce) = get_nonce()
> 
>         # validate nonce
>         assert _current_nonce = nonce
> 
> 
>         # This interface expects a signature pointer and length to make
>         # no assumption about signature validation schemes.
>         # But this implementation does, and it expects a (sig_r, sig_s) pair.
>         let sig_r = signature[0]
>         let sig_s = signature[1]
> 
>         verify_eth_signature(
>             msg_hash=hash,
>             r=sig_r,
>             s=sig_s,
>             v=0,
>             eth_address=_public_key)
> 
>         return ()
> end
> ```
> 
> But that returns:
> 
> ```
> starkware.cairo.lang.compiler.preprocessor.preprocessor_error.PreprocessorError: /com.docker.devenvironments.code/src/contracts/EthAccount.cairo:93:13: Unexpected implicit argument 'keccak_ptr' in an external function.
> E                           keccak_ptr : felt*
> E                           ^********^
> ```
> 
> And if I don't include keccak_ptr it throws:
> 
> ```
> E           starkware.cairo.lang.compiler.preprocessor.preprocessor_error.PreprocessorError: /com.docker.devenvironments.code/src/contracts/EthAccount.cairo:112:9: While trying to retrieve the implicit argument 'keccak_ptr' in:
> E                   verify_eth_signature(
> E                   ^*******************^
> E           /com.docker.devenvironments.code/.tox/default/lib/python3.7/site-packages/starkware/cairo/common/cairo_secp/signature.cairo:209:75: Unknown identifier 'keccak_ptr'.
> E           func verify_eth_signature{range_check_ptr, bitwise_ptr : BitwiseBuiltin*, keccak_ptr : felt*}(
> E         
>                                                                         ^****************^
> ```
> 
> Do you know how can I solve this?

Hey :)
Of course! You will need to do something like that:
```cairo
let (local keccak_ptr : felt*) = alloc()
let keccak_ptr_start = keccak_ptr

verity_eth_signature{keccak_ptr=keccak_ptr}(...)
```

Basically declaring the pointer before calling the function, and then calling the function and passing in the hint! :)

**Comment by JulissaDantes** [comment]
Thanks a lot, I should have remember that. I'll close the issue, thanks again for the help.
