### ISSUE TITLE
Recoreded tutorials cannot be found (404 page not found)

### ISSUE THREAD

**Issue by zingero** [starkware-libs/cairo-lang#79]
Hi,
As mentioned in the title, the [link](https://starknet.io/recorded-tutorials/) is unfortunately broken.

Is there another way to reach those tutorials?

Thanks ahead!

**Comment by eddymdz** [comment]
@zingero try with this link: https://starknet.io/recorded-talks/

**Comment by zingero** [comment]
Great, thanks
