### ISSUE TITLE
Cannot install cairo on windows 10

### ISSUE THREAD

**Issue by txthanh1178793** [starkware-libs/cairo-lang#86]
I received error "Could not find a version that satisfies the requirement ipfshttpclient==0.8.0a2 (from Web3->cairo-lang==0.9.1) (from versions: 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.13.1, 0.4.13.2, 0.6.0, 0.6.0.post1, 0.6.1)
No matching distribution found for ipfshttpclient==0.8.0a2 (from Web3->cairo-lang==0.9.1)" when install cairo from package cairo-lang-0.9.1.zip on windows 10.

**Comment by Shinwari536** [comment]
Hi @txthanh1178793 
It is not a perfect solution but can help. Use VMWare on your Windows10 and install Ubuntu on it. I suggest this because it is built for Linux systems, you may face some other issues while working in Cairo in Windows as OS.
